# Generated by Django 3.2.13 on 2022-06-22 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweettreats', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.AddField(
            model_name='post',
            name='ingredients',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='prepatation_time',
            field=models.CharField(default=0, max_length=30),
        ),
        migrations.AddField(
            model_name='post',
            name='serving_size',
            field=models.CharField(default=0, max_length=30),
        ),
    ]
