# Generated by Django 3.2.13 on 2022-06-23 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweettreats', '0003_rename_prepatation_time_post_preparation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='ingredients',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='instructions',
            field=models.TextField(),
        ),
    ]
