# Generated by Django 3.2.13 on 2022-06-24 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sweettreats', '0005_alter_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='excerpt',
        ),
    ]
