# Generated by Django 3.2.13 on 2022-07-17 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sweettreats', '0007_alter_post_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='email',
        ),
    ]
